# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       nload

# >> macros
# << macros
%define __requires_exclude ^libform|libncurses|libtinfo.*$

Summary:    Monitors network traffic and bandwidth usage in real time
Version:    0.7.4.180309
Release:    7
Group:      Applications/System
License:    GPLv2
URL:        http://www.roland-riegel.de/nload/index_en.html
Source0:    %{name}-%{version}.tar.gz
Source1:    files/%{name}.desktop
Source2:    files/%{name}.svgz
Source3:    files/%{name}_86.png
Source4:    files/%{name}_108.png
Source5:    files/%{name}_128.png
Source6:    files/%{name}_172.png
Source7:    files/%{name}_256.png
Source8:    files/%{name}_512.png
Source100:  nload.yaml
Patch0:     02_tinfo.patch
Patch1:     06_pr.patch
Patch2:     09_pr.patch
Requires:   ncurses-libs >= 5.0
BuildRequires:  pkgconfig(ncursesw) >= 5.0
BuildRequires:  automake
BuildRequires:  autoconf
BuildRequires:  python
BuildRequires:  desktop-file-utils
Obsoletes:   openrepos-%{name} < %{version}

%description
nload is a console application which monitors network traffic and bandwidth
usage in real time. It visualizes the in and outgoing traffic using two graphs
and provides additional info like total amount of transfered data and min/max
network usage.


%prep
%setup -q -n %{name}-%{version}/upstream


# 02_tinfo.patch
%patch0 -p1

# 06_pr.patch
%patch1 -p1

# 09_pr.patch
%patch2 -p1
# >> setup
# << setup

%build
# >> build pre
# run_autotools
# SFOS 4.3 does not have that macro?
#%%{__aclocal}
aclocal
%{__autoheader}
%{__autoconf}
%{__automake} --add-missing --copy
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
%{__install} -p -D -m 644 %SOURCE1 %{buildroot}%{_datadir}/applications/%{name}.desktop
%{__install} -p -D -m 644 %SOURCE2 %{buildroot}%{_datadir}/icons/hicolor/scalable/apps/%{name}.svgz
%{__install} -p -D -m 644 %SOURCE3 %{buildroot}%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{__install} -p -D -m 644 %SOURCE4 %{buildroot}%{_datadir}/icons/hicolor/108x108/apps/%{name}.png
%{__install} -p -D -m 644 %SOURCE5 %{buildroot}%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{__install} -p -D -m 644 %SOURCE6 %{buildroot}%{_datadir}/icons/hicolor/172x172/apps/%{name}.png
%{__install} -p -D -m 644 %SOURCE7 %{buildroot}%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
%{__install} -p -D -m 644 %SOURCE8 %{buildroot}%{_datadir}/icons/hicolor/512x512/apps/%{name}.png
# disable man pages
rm -rf %{buildroot}%{_mandir}
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/%{name}
%{_datadir}/icons/hicolor/*/apps/%{name}.png
%{_datadir}/icons/hicolor/scalable/apps/%{name}.svgz
%{_datadir}/applications/%{name}.desktop
# >> files
# << files
